language: python
sudo: false
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py35
    - TOXENV=pypy

addons:
  apt:
    sources:
      - pypy
    packages:
      - pypy

install:
    - export PATH=/usr/bin:$PATH
    - pip install tox

script: tox
